#!/usr/bin/env python3
"""
Create your own Consent O Matic rules repository
"""

import json
import os
from datetime import datetime

def create_custom_schema():
    """Create a custom schema for your rules."""
    
    schema = {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "CMP Mapper Custom Rules Schema",
        "description": "Custom Consent O Matic rules generated by CMP Mapper",
        "type": "object",
        "properties": {
            "$schema": {
                "type": "string",
                "description": "Schema reference URL"
            },
            "site_name": {
                "type": "object",
                "description": "Rule for a specific website",
                "properties": {
                    "detectors": {
                        "type": "object",
                        "properties": {
                            "presentMatcher": {
                                "type": "object",
                                "properties": {
                                    "type": {"type": "string", "enum": ["css"]},
                                    "target": {
                                        "type": "object",
                                        "properties": {
                                            "selector": {"type": "string"}
                                        }
                                    }
                                }
                            },
                            "showingMatcher": {
                                "type": "object",
                                "properties": {
                                    "type": {"type": "string", "enum": ["css"]},
                                    "target": {
                                        "type": "object",
                                        "properties": {
                                            "selector": {"type": "string"}
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "methods": {
                        "type": "object",
                        "patternProperties": {
                            "^(HIDE_CMP|DO_CONSENT|DO_REJECT|OPEN_OPTIONS|SAVE_CONSENT)$": {
                                "type": "object",
                                "properties": {
                                    "action": {
                                        "type": "object",
                                        "properties": {
                                            "type": {"type": "string", "enum": ["click", "hide", "wait"]},
                                            "target": {
                                                "type": "object",
                                                "properties": {
                                                    "selector": {"type": "string"}
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    
    return schema

def create_repository_structure():
    """Create the repository structure with all your rules."""
    
    # Create directory structure
    os.makedirs("custom-consent-o-matic-rules", exist_ok=True)
    os.makedirs("custom-consent-o-matic-rules/rules", exist_ok=True)
    
    # Create schema
    schema = create_custom_schema()
    with open("custom-consent-o-matic-rules/rules.schema.json", 'w', encoding='utf-8') as f:
        json.dump(schema, f, indent=2, ensure_ascii=False)
    
    # Create README
    readme_content = """# Custom Consent O Matic Rules

This repository contains custom Consent O Matic rules generated by CMP Mapper for various websites.

## 🎯 Available Rules

| Website | Rule File | Description |
|---------|-----------|-------------|
| Margis Pharmacy | [margispharmacy.json](rules/margispharmacy.json) | CookieYes banner with accept/reject |
| Midtown Compounding Pharmacy | [midtowncompoundingpharmacy.json](rules/midtowncompoundingpharmacy.json) | Custom banner with accept button |
| BeyondRX | [beyondrx.json](rules/beyondrx.json) | Shopify cookie banner |
| Westmount Medical Pharmacy | [westmountmedicalpharmacy.json](rules/westmountmedicalpharmacy.json) | CookieYes banner with full customization |

## 🚀 How to Use

1. **Copy the raw URL** of any rule file
2. **Open Consent O Matic** extension
3. **Go to 'GDPR Consent Rules Editor'**
4. **Click 'From URL'** and paste the raw URL
5. **Click 'Load'** to import the rule
6. **Click 'Save Custom Rule'** to make it permanent

## 📋 Raw URLs

- Margis Pharmacy: `https://raw.githubusercontent.com/[your-username]/consent-o-matic-rules/master/rules/margispharmacy.json`
- Midtown Compounding Pharmacy: `https://raw.githubusercontent.com/[your-username]/consent-o-matic-rules/master/rules/midtowncompoundingpharmacy.json`
- BeyondRX: `https://raw.githubusercontent.com/[your-username]/consent-o-matic-rules/master/rules/beyondrx.json`
- Westmount Medical Pharmacy: `https://raw.githubusercontent.com/[your-username]/consent-o-matic-rules/master/rules/westmountmedicalpharmacy.json`

## 🔧 Generated by CMP Mapper

These rules were automatically generated by [CMP Mapper](https://github.com/keyfive5/CMPMapper) - a tool for detecting cookie consent banners and generating Consent O Matic rules.

## 📝 Contributing

Feel free to submit issues or pull requests to improve these rules!
"""
    
    with open("custom-consent-o-matic-rules/README.md", 'w', encoding='utf-8') as f:
        f.write(readme_content)
    
    return "custom-consent-o-matic-rules"

def copy_existing_rules():
    """Copy your existing rules to the repository structure."""
    
    # List of existing rules to copy
    existing_rules = [
        "data/consent_o_matic_rules/margispharmacy_consent_o_matic.json",
        "data/consent_o_matic_rules/beyondrx_consent_o_matic.json",
        "data/consent_o_matic_rules/westmount_medical_pharmacy_20251022_232512.json"
    ]
    
    # Copy rules with simplified names
    rule_mappings = {
        "margispharmacy_consent_o_matic.json": "margispharmacy.json",
        "beyondrx_consent_o_matic.json": "beyondrx.json", 
        "westmount_medical_pharmacy_20251022_232512.json": "westmountmedicalpharmacy.json"
    }
    
    for old_path in existing_rules:
        if os.path.exists(old_path):
            # Get the new filename
            old_filename = os.path.basename(old_path)
            new_filename = rule_mappings.get(old_filename, old_filename)
            
            # Copy the file
            new_path = f"custom-consent-o-matic-rules/rules/{new_filename}"
            
            with open(old_path, 'r', encoding='utf-8') as f:
                content = f.read()
            
            with open(new_path, 'w', encoding='utf-8') as f:
                f.write(content)
            
            print(f"✅ Copied: {old_filename} → {new_filename}")
        else:
            print(f"⚠️  Not found: {old_path}")

def create_midtown_rule():
    """Create a simplified rule for Midtown Compounding Pharmacy."""
    
    midtown_rule = {
        "$schema": "https://raw.githubusercontent.com/[your-username]/consent-o-matic-rules/master/rules.schema.json",
        "MidtownCompoundingPharmacy": {
            "detectors": {
                "presentMatcher": {
                    "type": "css",
                    "target": {
                        "selector": ".widget.widget-cookie-banner.widget-cookie-banner-cookie-1"
                    }
                },
                "showingMatcher": {
                    "type": "css",
                    "target": {
                        "selector": ".widget.widget-cookie-banner.widget-cookie-banner-cookie-1"
                    }
                }
            },
            "methods": {
                "HIDE_CMP": {
                    "action": {
                        "type": "hide",
                        "target": {
                            "selector": ".widget.widget-cookie-banner.widget-cookie-banner-cookie-1"
                        }
                    }
                },
                "DO_CONSENT": {
                    "action": {
                        "type": "click",
                        "target": {
                            "selector": "[data-ux-btn='primary']"
                        }
                    }
                },
                "SAVE_CONSENT": {
                    "action": {
                        "type": "click",
                        "target": {
                            "selector": "[data-ux-btn='primary']"
                        }
                    }
                }
            }
        }
    }
    
    with open("custom-consent-o-matic-rules/rules/midtowncompoundingpharmacy.json", 'w', encoding='utf-8') as f:
        json.dump(midtown_rule, f, indent=2, ensure_ascii=False)
    
    print("✅ Created: midtowncompoundingpharmacy.json")

def main():
    """Create your custom repository structure."""
    
    print("🚀 Creating Your Custom Consent O Matic Rules Repository")
    print("=" * 70)
    
    # Create repository structure
    repo_path = create_repository_structure()
    print(f"📁 Created repository structure: {repo_path}")
    
    # Copy existing rules
    print("\n📋 Copying existing rules...")
    copy_existing_rules()
    
    # Create Midtown rule
    print("\n🏥 Creating Midtown Compounding Pharmacy rule...")
    create_midtown_rule()
    
    print(f"\n🎉 Repository created successfully!")
    print(f"📁 Location: {repo_path}")
    print(f"\n📋 Next Steps:")
    print(f"1. Upload the '{repo_path}' folder to GitHub")
    print(f"2. Make the repository public")
    print(f"3. Update the schema URLs in your rules")
    print(f"4. Share the raw URLs with others!")
    
    print(f"\n🔗 Example Raw URLs (after uploading to GitHub):")
    print(f"   • https://raw.githubusercontent.com/[your-username]/consent-o-matic-rules/master/rules/margispharmacy.json")
    print(f"   • https://raw.githubusercontent.com/[your-username]/consent-o-matic-rules/master/rules/westmountmedicalpharmacy.json")
    print(f"   • https://raw.githubusercontent.com/[your-username]/consent-o-matic-rules/master/rules/midtowncompoundingpharmacy.json")

if __name__ == "__main__":
    main()
